server:

  port: 8888

spring:

  application:

    name: config-server

  cloud:

    config:

      server:

        git:

          uri: https://github.com/alexrg91/bootCamp-ConfigServer2

          search-paths:

          - '*service*'

        default-label: main